### ISSUE TITLE
Includes misbehaving

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/oss-guides#12]
In .rubocop.ribose.yml, I've had to include the final line in the following, to get it to pick up ruby files at all:

````
AllCops:
  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/*.gemfile"
  - "**/Rakefile"
  - "**/*.rb"
````

**Comment by skalee** [comment]
Sorry for overlooking this one.

It looks like something has changed in Rubocop in version 0.56 ([changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0560-2018-05-14)). In version 0.55 .rb files are checked without this change.

Hound CI uses 0.54, hence is not affected by this issue. For now…

**Comment by skalee** [comment]
As far as I can see, they made improvements already—see `inherit_mode` in [Rubocop docs](https://rubocop.readthedocs.io/en/latest/configuration) (unfortunately, description is scattered in several subsections).

Nevertheless, I would rather remove `Include` section entirely. I don't see much benefit in keeping it, I guess it's some legacy piece of configuration. As of version 0.54 (currently run in Hound CI), [Rubocop's defaults](https://github.com/rubocop-hq/rubocop/blob/v0.54.0/config/default.yml) are far more comprehensive, and that remains true in ongoing versions. Alternatively, we could copy these defaults to `rubocop.ribose.yml` in order to freeze them.

I have made a pull request already—#19.

**Comment by opoudjis** [comment]
... But will we be enforcing it?

**Comment by skalee** [comment]
I wasn't thinking too much about it yet. I suppose it's a good idea, but perhaps there are some consequences I don't see yet.
