### ISSUE TITLE
No Rails checks

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/oss-guides#34]
Checks such as:

`Rails/Blank: Use `t["id"].blank?` instead of `t["id"].nil? || t["id"].empty?`.`

should not be invoked in our Rubocop: we are not doing Rails development, and non-Rails Ruby does not have `.blank?`.

**Comment by skalee** [comment]
I'm not sure if we're not doing Rails development indeed (@ronaldtse?). And even if so, there are gems like `attr_masker` which depend on some parts of Rails and for which such checks make sense.

I think that we can disable Rails checks here. This will prevent us from configuring Rails checks in our style guide (as in some cases it could enable particular checks), but actually I don't think it would be a problem.

That said, I suggest explicitly enabling/disabling Rails checks in particular projects rather than doing that here. This can be achieved by adding these two lines to every project's `.rubocop.yml`:

```
Rails:
  Enabled: false
```

It doesn't seem cumbersome, but please let me know if I'm wrong.

**Comment by opoudjis** [comment]
I think manually updating .rubocop.yml in over a hundred gems is the very definition of cumbersome. Clearly Rails checks should be the exception and not the default in Ribose development, so Rails checking should be opt in, not opt out. But I do need a decision one way or the other.

**Comment by ronaldtse** [comment]
Why don’t we make the default non Rails and opt in for Rails?

**Comment by skalee** [comment]
> I think manually updating .rubocop.yml in over a hundred gems is the very definition of cumbersome.

Got it.

> Why don’t we make the default non Rails and opt in for Rails?

I'm just worried that over time someone will explicitly enable some check from the Rails department in Thoughtbot's guide. Not going into details, this would make them getting into our style guide too, whereas disabling Rails checks on project's level would still work.

This isn't a strong argument, obviously. Such circumstances are unlikely, fixing that is easy, and even if undetected, damage would be insignificant. There is visible pressure on making Rails checks disabled by default, so let's disable them.

**Comment by skalee** [comment]
Fixed in #43.
